variables:
  SMOKE_TEST_HOST: https://frontend.dev.concept-and-craft.develop-test-alterrasoft.com/
  SMOKE_TEST_URI: /
  SMOKE_TEST_EXPECTED_STATUS_CODE: 200

stages:
  - install-deps
  - build
  - smoke-test

before_script:
  - echo "Before script"
  - cp -R $CI_PROJECT_DIR/* /opt/$CI_PROJECT_NAME
  - cd /opt/$CI_PROJECT_NAME

install-deps:
  stage: install-deps
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

smoke-test:
  stage: smoke-test
  script:
    - "[[ $(curl -I $SMOKE_TEST_HOST$SMOKE_TEST_URI 2>/dev/null | head -n 1 | cut -d$' ' -f2) == *$SMOKE_TEST_EXPECTED_STATUS_CODE* ]] || exit 1" 